version: '3.4'
services:
  traefik: 
    command: "--web --docker --docker.domain=docker.localhost --logLevel=DEBUG"
    image: traefik
    ports: 
      - "80:80"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dev/null:/traefik.toml"

  client:
    build:
      context: ./client
    labels: 
      - traefik.backend=client
      - "traefik.frontend.rule=Host:${DOMAIN_HOST}"

  api: 
    build: 
      context: ./api
    labels: 
      - traefik.backend=api
      - "traefik.frontend.rule=Host:${DOMAIN_HOST};PathPrefix:/api"
    links:
      - "redis:redis"
    depends_on: 
      - redis

  redis: 
    image: redis:5.0.0-alpine