const {
    REACT_APP_GOOGLE_API_KEY,
    REACT_APP_COUNTRIES_API_URL,
    REACT_APP_GOOGLE_GEOCODING_API_URL
} = process.env;

export {
    REACT_APP_GOOGLE_API_KEY,
    REACT_APP_COUNTRIES_API_URL,
    REACT_APP_GOOGLE_GEOCODING_API_URL
}